namespace Server.Game.objects.enums
{
    enum ShipAbilities
    {
        SHIP_ABILITY_SOLACE_INSTANT_HEAL = 1,

        SHIP_ABILITY_DIMINISHER_WEAKEN_SHIELDS = 2,

        SHIP_ABILITY_SPECTRUM_PRISMATIC_SHIELDING = 3,

        SHIP_ABILITY_SENTINEL_FORTRESS = 4,

        SHIP_ABILITY_VENOM_SINGULARITY = 5,

        SHIP_ABILITY_LIGHTNING_AFTERBURNER = 6,

        SHIP_ABILITY_SPEED_DEBUFF = 7,

        SHIP_ABILITY_AEGIS_HEALING_BEAM = 101,

        SHIP_ABILITY_AEGIS_SHIELD_RECHARGE = 104,

        SHIP_ABILITY_AEGIS_HEALING_POD = 105,

        SHIP_ABILITY_CITADEL_DRAW_FIRE = 102,

        SHIP_ABILITY_CITADEL_TRAVEL_MODE = 107,

        SHIP_ABILITY_CITADEL_PROTECTION = 108,

        SHIP_ABILITY_CITADEL_FORTIFY = 109,

        SHIP_ABILITY_SPEARHEAD_ULTIMATE_CLOAKING = 103,

        SHIP_ABILITY_SPEARHEAD_MARK_TARGET = 106,

        SHIP_ABILITY_SPEARHEAD_JAMX = 110,

        SHIP_ABILITY_SPEARHEAD_DOUBLE_MINIMAP_REVEAL = 111,

        NPC_ABILITY_HALLOWEEN_STICKYBOMB = 1000
    }
}