using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NettyBaseReloaded.WebSocks.objects
{
    class Admin
    {
        /* Admin Infos */
        public int UserId;

        public int PlayerId;

        /* Name for chat and admin panel */
        public string AdminName;

        /* Admin access level */
        public int AccessLevel;

        /* Auth key for verification generated by server representing the following inside [userid.tostring() + playerid.tostring() + sessionId] */
        public string AuthKey;

        /* Session ID for verification */
        public string SessionId;

        /* Time admin logged in*/
        public DateTime TimeOfAuth;

        public Admin(int userId, int playerId, string sessionId, DateTime authTime)
        {
            UserId = userId;
            PlayerId = playerId;
            SessionId = sessionId;
            TimeOfAuth = authTime;
        }

        public void BeginAuth()
        {
            //todo
        }

        public bool VerifyAuth(string authKey)
        {
            return false;
        }
    }
}
