namespace NettyBaseReloaded.Game.objects.world.players.settings
{
    enum Buttons
    {
        ACTION_ACTIVATE_GATE = 2,

        ACTION_SHOW_SETTINGS_WINDOW = 8,

        ACTION_LOGOUT = 9,

        ACTION_TRADE = 10,

        ACTION_HELP = 25,

        ACTION_FASTREPAIR = 34,

        ACTION_FULLSCREEN = 104,

        ACTION_COMPANY_HIERARCHY = 105,

        ACTIVATION_LASER = 0,

        SELECTION_LASER_X1 = 3,

        SELECTION_LASER_X2 = 4,

        SELECTION_LASER_X3 = 5,

        SELECTION_LASER_X4 = 6,

        SELECTION_LASER_SAB50 = 7,

        SELECTION_LASER_RSB75 = 39,

        SELECTION_LASER_CBO100 = 8,

        SELECTION_LASER_JOB100 = 108,

        ACTIVATION_ROCKET = 1,

        SELECTION_ROCKET_R_310 = 11,

        SELECTION_ROCKET_PLT_2026 = 12,

        SELECTION_ROCKET_PLT_2021 = 13,

        SELECTION_ROCKET_PLT_3030 = 57,

        SELECTION_ROCKET_BDR_1211 = 74,

        SELECTION_ROCKET_PLD_8 = 44,

        SELECTION_ROCKET_DCR_250 = 72,

        SELECTION_ROCKET_WIZ = 43,

        SELECTION_LOAD_ROCKET_LAUNCHER = 46,

        SELECTION_LAUNCHER_ROCKET_HST01 = 48,

        SELECTION_LAUNCHER_ROCKET_UBR100 = 49,

        SELECTION_LAUNCHER_ROCKET_ECO10 = 50,

        SELECTION_LAUNCHER_ROCKET_SAR_01 = 75,

        SELECTION_LAUNCHER_ROCKET_SAR_02 = 76,

        SELECTION_LAUNCHER_ROCKET_CBR = 102,

        SELECTION_LAUNCHER_ROCKET_BDR_1212 = 109,

        ACTIVATION_CHAIN_BOLT = 51,

        ACTIVATION_TECH = 52,

        ACTIVATION_SHIELD_BACKUP = 53,

        ACTIVATION_ENERGY_LEECH = 54,

        ACTIVATION_ROCKET_PRECISION = 55,

        ACTIVATION_BATTLE_REP_BOT = 59,

        ACTIVATION_SPEED_LEECH = 60,

        ACTIVATION_SKILL_SOLACE = 63,

        ACTIVATION_SKILL_DIMINISHER = 64,

        ACTIVATION_SKILL_SPECTRUM = 65,

        ACTIVATION_SKILL_SENTINEL = 66,

        ACTIVATION_SKILL_VENOM = 67,

        ACTIVATION_SKILL_LIGHTNING = 73,

        ACTIVATION_EXPLOSIVE = 14,

        SELECTION_MINE = 15,

        SELECTION_MINE_EMP = 68,

        SELECTION_MINE_SAB = 69,

        SELECTION_MINE_DDM = 70,

        SELECTION_MINE_SLM = 103,

        SELECTION_EMP = 45,

        SELECTION_SMARTBOMB = 16,

        SELECTION_INSTASHIELD = 17,

        ACTIVATION_CPU_JUMP = 20,

        ACTIVATION_CPU_CLOAK = 21,

        ACTIVATION_CPU_AROL = 22,

        ACTIVATION_CPU_ROBOT = 23,

        ACTIVATION_CPU_AIM = 24,

        ACTIVATION_CPU_HM7 = 35,

        ACTIVATION_CPU_DRONE_REPAIR = 41,

        ACTIVATION_CPU_AMMOBUY = 42,

        ACTIVATION_CPU_RLLB = 47,

        ACTIVATION_CPU_ROCKETBUY = 56,

        SELECT_CPU_JUMP_TARGET = 71,

        ACTIVATION_CPU_FUELBUY = 18,

        ACTIVATION_BUY = 25,

        BUY_LASER_1 = 26,

        BUY_LASER_2 = 27,

        BUY_LASER_3 = 28,

        BUY_LASER_4 = 29,

        BUY_LASER_5 = 30,

        BUY_ROCKET_R_310 = 31,

        BUY_ROCKET_PLT_2026 = 32,

        BUY_ROCKET_PLT_2021 = 33,

        BUY_ROCKET_PLT_3030 = 58,

        SELECTION_FIREWORK_1 = 36,

        SELECTION_FIREWORK_2 = 37,

        SELECTION_FIREWORK_3 = 38,

        FIREWORK_IGNITE = 40,

        ACTIVATION_FORMATION_STD = 77,

        ACTIVATION_FORMATION_TURTLE = 78,

        ACTIVATION_FORMATION_ARROW = 79,

        ACTIVATION_FORMATION_LANCE = 80,

        ACTIVATION_FORMATION_STAR = 81,

        ACTIVATION_FORMATION_PINCER = 82,

        ACTIVATION_FORMATION_DOUBLE_ARROW = 83,

        ACTIVATION_FORMATION_DIAMOND = 84,

        ACTIVATION_FORMATION_CHEVRON = 85,

        ACTIVATION_FORMATION_MOTH = 86,

        ACTIVATION_FORMATION_CRAB = 87,

        ACTIVATION_FORMATION_HEART = 88,

        ACTIVATION_FORMATION_BARRAGE = 89,

        ACTIVATION_FORMATION_BAT = 106,

        ACTIVATION_FORMATION_MOSQUITO = 107,

        ACTIVATION_SKILL_AEGIS_HP_REPAIR = 90,

        ACTIVATION_SKILL_CITADEL_DRAW_FIRE = 91,

        ACTIVATION_SKILL_SPEARHEAD_ULTIMATE_CLOAKING = 92,

        ACTIVATION_SKILL_AEGIS_SHIELD_RECHARGE = 93,

        ACTIVATION_SKILL_AEGIS_HEALING_POD = 94,

        ACTIVATION_SKILL_SPEARHEAD_MARK_TARGET = 95,

        ACTIVATION_SKILL_CITADEL_TRAVEL_MODE = 96,

        ACTIVATION_SKILL_CITADEL_PROTECTION_POD = 97,

        ACTIVATION_SKILL_CITADEL_FORTIFY = 98,

        ACTIVATION_SKILL_SPEARHEAD_ULTIMATE_EMP = 99,

        ACTIVATION_SKILL_SPEARHEAD_DOUBLE_MINIMAP_REVEAL = 100,

        ACTION_SHIP_WARP_WINDOW = 101
    }
}
