using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QuestBuilder.quests
{
    enum QuestConditions
    {
        QUESTCASE = 0,
        TIMER = 1,
        HASTE = 2,
        ENDURANCE = 3,
        COUNTDOWN = 4,
        COLLECT = 5,
        KILL_NPC = 6,
        DAMAGE = 7,
        AVOID_DAMAGE = 8,
        TAKE_DAMAGE = 9,
        AVOID_DEATH = 10,
        COORDINATES = 11,
        DISTANCE = 12,
        TRAVEL = 13,
        FUEL_SHORTAGE = 14,
        PROXIMITY = 15,
        MAP = 16,
        MAP_DIVERSE = 17,
        EMPTY = 18,
        MISCELLANEOUS = 19,
        AMMUNITION = 20,
        SAVE_AMMUNITION = 21,
        SPEND_AMMUNITION = 22,
        SALVAGE = 23,
        STEAL = 24,
        KILL = 25,
        DEAL_DAMAGE = 26,
        KILL_NPCS = 27,
        KILL_PLAYERS = 28,
        DAMAGE_NPCS = 29,
        DAMAGE_PLAYERS = 30,
        VISIT_MAP = 31,
        DIE = 32,
        AVOID_KILL_NPC = 33,
        AVOID_KILL_NPCS = 34,
        AVOID_KILL_PLAYERS = 35,
        AVOID_DAMAGE_NPCS = 36,
        AVOID_DAMAGE_PLAYERS = 37,
        PREVENT = 38,
        JUMP = 39,
        AVOID_JUMP = 40,
        STEADINESS = 41,
        MULTIPLIER = 42,
        STAY_AWAY = 43,
        IN_GROUP = 44,
        KILL_ANY = 45,
        WEB = 46,
        CLIENT = 47,
        CARGO = 48,
        SELL_ORE = 49,
        LEVEL = 50,
        USER_DEFINED = 51,
        COLLECT_BONUS_BOX = 52,
        UPGRADE = 53,
        FINISH_QUEST = 54,
        QUICK_BUY = 55,
        ENTER_GROUP = 56,
        RESTRICT_AMMUNITION_KILL_NPC = 57,
        RESTRICT_AMMUNITION_KILL_PLAYER = 58,
        KILL_PLAYER = 59,
        VISIT_QUEST_GIVER = 60,
        REAL_TIME_HASTE = 61,
        SPECIAL_HONOUR = 62
    }
}
